### ISSUE TITLE
Settings for more flexible integrations

### ISSUE THREAD

**Issue by glombek** [kurtnovack/stickytoolbar#3]
The class for the top part is not always `.mce-top-part` and if the editor is within an element with an overflow, the `window` scroll event is not sufficent.

I suggest settings for:

- sticky_toolbar_container
- sticky_scrolling_container (default to `window`)
- sticky_statusbar_container

I'll create a pull request myself if I get the time.

**Comment by keyranova** [comment]
I swear this is not dead, I just get to it when work dies down.
I've added `sticky_toolbar_container`, `sticky_menubar_container`, `sticky_statusbar_container`, and `sticky_scrolling_container` as options
