### ISSUE TITLE
Toolbars have new class

### ISSUE THREAD

**Issue by michalmarek** [kurtnovack/stickytoolbar#8]
TinyMCE 5.0.7 - toolbars have new class .tox-toolbar-overlord instead of .tox-toolbar - it is needed to change it in source files, or make option for configure it externaly (another issue here).

**Comment by keyranova** [comment]
Looks like it has the overlord class if your settings have two toolbars but not if they have one. I've added the option `sticky_toolbar_container` so you can set any class name that you need.
